"""Native chess and Go search, inference, and game bindings."""

from __future__ import annotations

__all__ = [
    'AnalysisMode',
    'AnalysisParameters',
    'AnalysisResult',
    'ActionAnalysisCandidate',
    'BatchedInferenceParameters',
    'BatchedSearchParameters',
    'CandidateAnalysis',
    'ChessSearchChild',
    'ChessSearchRoot',
    'ChessPosition',
    'ChessAnalysis',
    'ChessAnalysisSession',
    'ChessSelfPlaySearch',
    'ChessSelfPlaySearchBatch',
    'SelfPlaySearchParameters',
    'ChessSelfPlaySearchRequest',
    'ChessSelfPlaySearchResult',
    'SelfPlaySearchStatistics',
    'GameSearchResult',
    'GameSearchVisit',
    'GameAnalysisResult',
    'FirstPlayUrgencyKind',
    'FirstPlayUrgencyParameters',
    'GoAreaScore',
    'GoAnalysis7',
    'GoAnalysis9',
    'GoSelfPlaySearch7',
    'GoSelfPlaySearch9',
    'GoSelfPlaySearchRequest7',
    'GoSelfPlaySearchRequest9',
    'GoSelfPlaySearchResult7',
    'GoSelfPlaySearchResult9',
    'GoSelfPlaySearchBatch7',
    'GoSelfPlaySearchBatch9',
    'GoPlayer',
    'GoPosition7',
    'GoPosition9',
    'GoRules',
    'GoSearchRoot7',
    'GoSearchRoot9',
    'GoTerminalResult',
    'GoTerminationReason',
    'InferenceDimensions',
    'InferenceDevice',
    'InferenceConfiguration',
    'InferenceStatistics',
    'TreeSearchParameters',
    'WdlPrediction',
    'encode_board_packed_bytes',
    'mirror_chess_action_id',
    'new_root',
]

class InferenceDimensions:
    def __init__(self, channels: int, rows: int, columns: int, actions: int, outcomes: int) -> None: ...
    @property
    def channels(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def columns(self) -> int: ...
    @property
    def actions(self) -> int: ...
    @property
    def outcomes(self) -> int: ...

class GameSearchVisit:
    def __init__(self, action_id: int, visit_count: int) -> None: ...
    @property
    def action_id(self) -> int: ...
    @property
    def visit_count(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class GameSearchResult:
    @property
    def root_value(self) -> float: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...

class ChessPosition:
    def __init__(self, fen: str = ...) -> None: ...
    @property
    def current_player(self) -> int: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def fen(self) -> str: ...
    def legal_actions(self) -> list[int]: ...
    def child(self, action_id: int) -> ChessPosition: ...
    def terminal_value(self) -> float: ...
    def approximate_result_score(self) -> float: ...
    def packed_encoding(self) -> bytes: ...

class BatchedSearchParameters:
    def __init__(
        self,
        parallel_searches: int,
        tree_search: TreeSearchParameters,
        dirichlet_alpha: float,
        dirichlet_epsilon: float,
        tree_capacity: int,
    ) -> None: ...

class FirstPlayUrgencyKind:
    ZERO: FirstPlayUrgencyKind
    PARENT_VALUE: FirstPlayUrgencyKind
    REDUCED_PARENT_VALUE: FirstPlayUrgencyKind

class FirstPlayUrgencyParameters:
    def __init__(self, kind: FirstPlayUrgencyKind, reduction: float = 0.0) -> None: ...
    kind: FirstPlayUrgencyKind
    reduction: float

class TreeSearchParameters:
    def __init__(
        self,
        exploration_constant: float,
        first_play_urgency: FirstPlayUrgencyParameters,
        forced_playout_coefficient: float,
        value_discount_per_ply: float,
    ) -> None: ...
    exploration_constant: float
    first_play_urgency: FirstPlayUrgencyParameters
    forced_playout_coefficient: float
    value_discount_per_ply: float

class BatchedInferenceParameters:
    def __init__(
        self,
        workers: int,
        batch_size: int,
        outstanding_batches_per_worker: int,
    ) -> None: ...
    workers: int
    batch_size: int
    outstanding_batches_per_worker: int

class AnalysisParameters:
    def __init__(
        self,
        parallel_searches: int,
        exploration_constant: float,
        inference: BatchedInferenceParameters,
    ) -> None: ...
    parallel_searches: int
    exploration_constant: float
    inference: BatchedInferenceParameters

class ActionAnalysisCandidate:
    @property
    def action_id(self) -> int: ...
    @property
    def policy_prior(self) -> float: ...
    @property
    def visits(self) -> int: ...
    @property
    def visit_share(self) -> float: ...
    @property
    def mean_value(self) -> float | None: ...

class GameAnalysisResult:
    @property
    def chosen_action_id(self) -> int: ...
    @property
    def value(self) -> float: ...
    @property
    def outcome(self) -> WdlPrediction | None: ...
    @property
    def candidates(self) -> list[ActionAnalysisCandidate]: ...
    @property
    def searches(self) -> int: ...
    @property
    def maximum_depth(self) -> int: ...
    @property
    def elapsed_milliseconds(self) -> int: ...
    @property
    def principal_variation(self) -> list[int]: ...

class GoPlayer:
    BLACK: GoPlayer
    WHITE: GoPlayer

class GoTerminationReason:
    ONGOING: GoTerminationReason
    TWO_PASSES: GoTerminationReason
    MAXIMUM_MOVES: GoTerminationReason
    @property
    def name(self) -> str: ...

class GoRules:
    def __init__(self, komi_half_points: int, maximum_moves: int) -> None: ...
    @property
    def komi_half_points(self) -> int: ...
    @property
    def maximum_moves(self) -> int: ...

class GoAreaScore:
    @property
    def black_half_points(self) -> int: ...
    @property
    def white_half_points(self) -> int: ...
    @property
    def winner(self) -> GoPlayer | None: ...

class GoTerminalResult:
    @property
    def reason(self) -> GoTerminationReason: ...
    @property
    def score(self) -> GoAreaScore: ...
    @property
    def winner(self) -> GoPlayer | None: ...

class GoPosition7:
    def __init__(self, rules: GoRules) -> None: ...
    @property
    def board_size(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    @property
    def player(self) -> GoPlayer: ...
    @property
    def is_terminal(self) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def child(self, action_id: int) -> GoPosition7: ...
    def black_points(self, history_offset: int) -> list[int]: ...
    def white_points(self, history_offset: int) -> list[int]: ...
    def packed_encoding(self) -> bytes: ...
    def terminal_result(self) -> GoTerminalResult: ...
    def terminal_value(self) -> float: ...

class GoPosition9:
    def __init__(self, rules: GoRules) -> None: ...
    @property
    def board_size(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    @property
    def player(self) -> GoPlayer: ...
    @property
    def is_terminal(self) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def child(self, action_id: int) -> GoPosition9: ...
    def black_points(self, history_offset: int) -> list[int]: ...
    def white_points(self, history_offset: int) -> list[int]: ...
    def packed_encoding(self) -> bytes: ...
    def terminal_result(self) -> GoTerminalResult: ...
    def terminal_value(self) -> float: ...

class GoSearchRoot7:
    @property
    def position(self) -> GoPosition7: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def visits(self) -> int: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def children(self) -> list[tuple[int, int]]: ...
    def play(self, action_id: int) -> None: ...

class GoSearchRoot9:
    @property
    def position(self) -> GoPosition9: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def visits(self) -> int: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def children(self) -> list[tuple[int, int]]: ...
    def play(self, action_id: int) -> None: ...

class GoSelfPlaySearchRequest7:
    def __init__(self, root: GoSearchRoot7, full_search: bool) -> None: ...
    root: GoSearchRoot7
    full_search: bool

class GoSelfPlaySearchResult7:
    root_value: float
    highest_visited_child_action_id: int
    highest_visited_child_visit_count: int
    highest_visited_child_q: float
    search_visits: list[GameSearchVisit]
    policy_target_visits: list[GameSearchVisit]
    root: GoSearchRoot7

class GoSelfPlaySearchBatch7:
    results: list[GoSelfPlaySearchResult7]
    statistics: SelfPlaySearchStatistics
    simulations_completed: int

class GoSelfPlaySearch7:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_generation: int = 0,
    ) -> None: ...
    @staticmethod
    def inference_dimensions() -> InferenceDimensions: ...
    def new_root(self, position: GoPosition7) -> GoSearchRoot7: ...
    def request(self, root: GoSearchRoot7, full_search: bool) -> GoSelfPlaySearchRequest7: ...
    def search(
        self, requests: list[GoSelfPlaySearchRequest7], collect_statistics: bool = False
    ) -> GoSelfPlaySearchBatch7: ...
    def refresh_model(self, model_generation: int, model_path: str) -> None: ...
    @property
    def model_generation(self) -> int: ...

class GoSelfPlaySearchRequest9:
    def __init__(self, root: GoSearchRoot9, full_search: bool) -> None: ...
    root: GoSearchRoot9
    full_search: bool

class GoSelfPlaySearchResult9:
    root_value: float
    highest_visited_child_action_id: int
    highest_visited_child_visit_count: int
    highest_visited_child_q: float
    search_visits: list[GameSearchVisit]
    policy_target_visits: list[GameSearchVisit]
    root: GoSearchRoot9

class GoSelfPlaySearchBatch9:
    results: list[GoSelfPlaySearchResult9]
    statistics: SelfPlaySearchStatistics
    simulations_completed: int

class GoSelfPlaySearch9:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_generation: int = 0,
    ) -> None: ...
    @staticmethod
    def inference_dimensions() -> InferenceDimensions: ...
    def new_root(self, position: GoPosition9) -> GoSearchRoot9: ...
    def request(self, root: GoSearchRoot9, full_search: bool) -> GoSelfPlaySearchRequest9: ...
    def search(
        self, requests: list[GoSelfPlaySearchRequest9], collect_statistics: bool = False
    ) -> GoSelfPlaySearchBatch9: ...
    def refresh_model(self, model_generation: int, model_path: str) -> None: ...
    @property
    def model_generation(self) -> int: ...

class GoAnalysis7:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        parameters: AnalysisParameters,
    ) -> None: ...
    def new_root(self, rules: GoRules) -> GoSearchRoot7: ...
    def analyze_policy(self, root: GoSearchRoot7) -> GameAnalysisResult: ...
    def analyze_counted(self, root: GoSearchRoot7, searches: int) -> GameAnalysisResult: ...
    def analyze_timed(self, root: GoSearchRoot7, seconds: int) -> GameAnalysisResult: ...
    def inference_statistics(self) -> InferenceStatistics: ...

class GoAnalysis9:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        parameters: AnalysisParameters,
    ) -> None: ...
    def new_root(self, rules: GoRules) -> GoSearchRoot9: ...
    def analyze_policy(self, root: GoSearchRoot9) -> GameAnalysisResult: ...
    def analyze_counted(self, root: GoSearchRoot9, searches: int) -> GameAnalysisResult: ...
    def analyze_timed(self, root: GoSearchRoot9, seconds: int) -> GameAnalysisResult: ...
    def inference_statistics(self) -> InferenceStatistics: ...

class AnalysisMode:
    POLICY: AnalysisMode
    MCTS: AnalysisMode

class WdlPrediction:
    @property
    def win(self) -> float: ...
    @property
    def draw(self) -> float: ...
    @property
    def loss(self) -> float: ...
    @property
    def value(self) -> float: ...

class CandidateAnalysis:
    @property
    def move_uci(self) -> str: ...
    @property
    def policy_prior(self) -> float: ...
    @property
    def visits(self) -> int: ...
    @property
    def visit_share(self) -> float: ...
    @property
    def mean_value(self) -> float | None: ...

class AnalysisResult:
    @property
    def chosen_move_uci(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def outcome(self) -> WdlPrediction | None: ...
    @property
    def candidates(self) -> list[CandidateAnalysis]: ...
    @property
    def searches(self) -> int: ...
    @property
    def maximum_depth(self) -> int: ...
    @property
    def elapsed_milliseconds(self) -> int: ...
    @property
    def principal_variation(self) -> list[str]: ...

class InferenceDevice:
    AUTO: InferenceDevice
    CPU: InferenceDevice
    CUDA: InferenceDevice

class ChessAnalysis:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        parameters: AnalysisParameters,
    ) -> None: ...
    def new_session(self, starting_fen: str, moves_uci: tuple[str, ...]) -> ChessAnalysisSession: ...
    def inference_statistics(self) -> InferenceStatistics: ...

class ChessAnalysisSession:
    def apply_move(self, move_uci: str) -> None: ...
    def analyze(
        self,
        mode: AnalysisMode,
        time_limit_seconds: int | None = None,
        search_limit: int | None = None,
    ) -> AnalysisResult: ...
    @property
    def fen(self) -> str: ...
    @property
    def starting_fen(self) -> str: ...
    @property
    def moves_uci(self) -> list[str]: ...
    @property
    def root_visits(self) -> int: ...

def encode_board_packed_bytes(fen: str) -> bytes:
    """Encode a FEN into the canonical packed plane-major byte layout."""

class InferenceConfiguration:
    device_id: int
    model_path: str
    device: InferenceDevice
    def __init__(
        self,
        device_id: int,
        model_path: str,
        device: InferenceDevice = InferenceDevice.AUTO,
    ) -> None: ...

class InferenceStatistics:
    def __init__(self) -> None: ...
    @property
    def averageNumberOfPositionsInInferenceCall(self) -> float: ...
    @property
    def evaluations(self) -> int: ...
    @property
    def modelBatchSizeHistogram(self) -> list[int]: ...
    @property
    def modelInferenceCalls(self) -> int: ...
    @property
    def modelInferencePositions(self) -> int: ...

class ChessSelfPlaySearch:
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_version: int = 0,
    ) -> None: ...
    @property
    def arena_capacity(self) -> int: ...
    @property
    def model_version(self) -> int: ...
    @property
    def model_generation(self) -> int: ...
    def request(self, root: ChessSearchRoot, full_search: bool) -> ChessSelfPlaySearchRequest: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def refresh_model(self, model_version: int, model_path: str) -> None: ...
    def update_search_schedule(self, search_parameters: SelfPlaySearchParameters) -> bool: ...
    def inference_with_history(
        self, histories: list[tuple[str, list[str]]]
    ) -> list[tuple[list[tuple[int, float]], float]]: ...
    def search(
        self,
        requests: list[ChessSelfPlaySearchRequest],
        collect_statistics: bool = False,
    ) -> ChessSelfPlaySearchBatch:
        """
        Run batched chess self-play search requests.
        Returns a ChessSelfPlaySearchBatch whose results contain:
            - root_value: float
            - visits: List of (encoded_move: int, visit_count: int)
            - root: the retained ChessSearchRoot
        """
    def new_root(self, position: ChessPosition) -> ChessSearchRoot: ...
    def new_root_with_history(
        self,
        starting_fen: str,
        moves_uci: tuple[str, ...],
    ) -> ChessSearchRoot: ...

class ChessSelfPlaySearchRequest:
    def __init__(self, root: ChessSearchRoot, full_search: bool) -> None: ...
    @property
    def root(self) -> ChessSearchRoot: ...
    @property
    def full_search(self) -> bool: ...

class ChessSearchChild:
    @property
    def encoded_move(self) -> int: ...
    @property
    def is_materialized(self) -> bool: ...
    @property
    @property
    def policy(self) -> float: ...
    @property
    def result_sum(self) -> float: ...
    @property
    def virtual_loss(self) -> float: ...
    @property
    def visits(self) -> int: ...

class ChessSearchRoot:
    def __repr__(self) -> str: ...
    def discount(self, percentage_of_node_visits_to_keep: float) -> None:
        """
        Discount the node's score and visits by a percentage.
        Descendant materializations are explicitly pruned when required by the fixed arena.
        """
    def make_new_root(self, child_index: int) -> ChessSearchRoot:
        """
        Prune the old tree and return a new root node.
        `child_index` is the index of the child to make the new root.
        """
    def play(self, action_id: int) -> None: ...
    def reset(self) -> None: ...
    @property
    def arena_capacity(self) -> int: ...
    @property
    def children(self) -> list[ChessSearchChild]: ...
    @property
    def fen(self) -> str: ...
    @property
    def is_expanded(self) -> bool: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def max_depth(self) -> int: ...
    @property
    def move(self) -> str: ...
    @property
    def repetition_count(self) -> int: ...
    @property
    def result_sum(self) -> float: ...
    @property
    def total_child_records(self) -> int: ...
    @property
    def virtual_loss(self) -> float: ...
    @property
    def visits(self) -> int: ...
    @property
    def position(self) -> ChessPosition: ...

class SelfPlaySearchParameters:
    tree_search: TreeSearchParameters
    dirichlet_alpha: float
    dirichlet_epsilon: float
    fast_searches: int
    full_searches: int
    parallel_searches: int
    def __init__(
        self,
        parallel_searches: int,
        full_searches: int,
        fast_searches: int,
        tree_search: TreeSearchParameters,
        dirichlet_alpha: float,
        dirichlet_epsilon: float,
    ) -> None: ...

class ChessSelfPlaySearchResult:
    @property
    def root_value(self) -> float: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def root(self) -> ChessSearchRoot: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...

class ChessSelfPlaySearchBatch:
    @property
    def statistics(self) -> SelfPlaySearchStatistics: ...
    @property
    def results(self) -> list[ChessSelfPlaySearchResult]: ...
    @property
    def simulations_completed(self) -> int: ...

class SelfPlaySearchStatistics:
    @property
    def average_depth(self) -> float: ...
    @property
    def average_entropy(self) -> float: ...
    @property
    def average_kl_divergence(self) -> float: ...
    @property
    def average_policy_search_kl_divergence(self) -> float: ...
    @property
    def top_action_disagreement(self) -> float: ...
    @property
    def selected_action_prior_rank(self) -> float: ...

def new_root(fen: str, arena_capacity: int) -> ChessSearchRoot:
    """
    Create a self-play MCTS root with an explicit fixed arena capacity.
    """

def new_root_with_history(
    starting_fen: str,
    moves_uci: tuple[str, ...],
    arena_capacity: int,
) -> ChessSearchRoot:
    """Create a fixed-capacity MCTS root by replaying bounded UCI history."""

def mirror_chess_action_id(action_id: int) -> int: ...
