"""
Native game search and inference
"""

from __future__ import annotations

import typing

import pybind11_stubgen.typing_ext

__all__: list[str] = [
    'ActionAnalysisCandidate',
    'AdditionalSearchLimit',
    'AnalysisMode',
    'AnalysisParameters',
    'AnalysisResult',
    'BatchedInferenceParameters',
    'BatchedSearchParameters',
    'CHESS_ACTION_SIZE',
    'CandidateAnalysis',
    'ChessAnalysis',
    'ChessAnalysisSession',
    'ChessPosition',
    'ChessSearchChild',
    'ChessSearchRoot',
    'ChessSelfPlaySearch',
    'ChessSelfPlaySearchBatch',
    'ChessSelfPlaySearchRequest',
    'ChessSelfPlaySearchResult',
    'FirstPlayUrgencyKind',
    'FirstPlayUrgencyParameters',
    'FixedSearchLimit',
    'GameAnalysisResult',
    'GameSearchResult',
    'GameSearchVisit',
    'GoAnalysis7',
    'GoAnalysis9',
    'GoAreaScore',
    'GoPlayer',
    'GoPosition7',
    'GoPosition9',
    'GoRules',
    'GoSearchRoot7',
    'GoSearchRoot9',
    'GoSelfPlaySearch7',
    'GoSelfPlaySearch9',
    'GoSelfPlaySearchBatch7',
    'GoSelfPlaySearchBatch9',
    'GoSelfPlaySearchRequest7',
    'GoSelfPlaySearchRequest9',
    'GoSelfPlaySearchResult7',
    'GoSelfPlaySearchResult9',
    'GoTerminalResult',
    'GoTerminationReason',
    'InferenceConfiguration',
    'InferenceDevice',
    'InferenceDimensions',
    'InferenceExecutionOptions',
    'InferenceMemoryFormat',
    'InferencePrecision',
    'InferenceStatistics',
    'OutcomeProbabilities',
    'PredictedSearchBudgetLimit',
    'SdpaBackend',
    'SearchBudgetCurve',
    'SearchCheckpoint',
    'SearchCheckpointDetail',
    'SearchStopReason',
    'SelfPlaySearchParameters',
    'SelfPlaySearchStatistics',
    'TreeSearchParameters',
    'WdlPrediction',
    'encode_board_packed_bytes',
    'mirror_chess_action_id',
    'new_root',
    'new_root_with_history',
    'search_budget_multiplier',
    'search_parallelism',
]

class ActionAnalysisCandidate:
    @property
    def action_id(self) -> int: ...
    @property
    def mean_value(self) -> float | None: ...
    @property
    def policy_prior(self) -> float: ...
    @property
    def visit_share(self) -> float: ...
    @property
    def visits(self) -> int: ...

class AdditionalSearchLimit:
    def __init__(self, additional_visits: int) -> None: ...
    @property
    def additional_visits(self) -> int: ...

class AnalysisMode:
    """
    Members:

      POLICY

      MCTS
    """

    MCTS: typing.ClassVar[AnalysisMode]  # value = <AnalysisMode.MCTS: 1>
    POLICY: typing.ClassVar[AnalysisMode]  # value = <AnalysisMode.POLICY: 0>
    __members__: typing.ClassVar[
        dict[str, AnalysisMode]
    ]  # value = {'POLICY': <AnalysisMode.POLICY: 0>, 'MCTS': <AnalysisMode.MCTS: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class AnalysisParameters:
    def __init__(
        self, parallel_searches: int, exploration_constant: float, inference: BatchedInferenceParameters
    ) -> None: ...
    @property
    def exploration_constant(self) -> float: ...
    @property
    def inference(self) -> BatchedInferenceParameters: ...
    @property
    def parallel_searches(self) -> int: ...

class AnalysisResult:
    @property
    def candidates(self) -> list[CandidateAnalysis]: ...
    @property
    def chosen_move_uci(self) -> str: ...
    @property
    def elapsed_milliseconds(self) -> int: ...
    @property
    def maximum_depth(self) -> int: ...
    @property
    def outcome(self) -> WdlPrediction | None: ...
    @property
    def principal_variation(self) -> list[str]: ...
    @property
    def searches(self) -> int: ...
    @property
    def value(self) -> float: ...

class BatchedInferenceParameters:
    def __init__(self, workers: int, batch_size: int, outstanding_batches_per_worker: int) -> None: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def outstanding_batches_per_worker(self) -> int: ...
    @property
    def workers(self) -> int: ...

class BatchedSearchParameters:
    def __init__(
        self,
        tree_search: TreeSearchParameters,
        dirichlet_alpha: float,
        dirichlet_epsilon: float,
        initial_tree_capacity: int,
        maximum_tree_capacity: int,
    ) -> None: ...

class CandidateAnalysis:
    @property
    def mean_value(self) -> float | None: ...
    @property
    def move_uci(self) -> str: ...
    @property
    def policy_prior(self) -> float: ...
    @property
    def visit_share(self) -> float: ...
    @property
    def visits(self) -> int: ...

class ChessAnalysis:
    def __init__(self, runtime_parameters: InferenceConfiguration, parameters: AnalysisParameters) -> None: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def new_session(self, starting_fen: str, moves_uci: list[str]) -> ChessAnalysisSession: ...

class ChessAnalysisSession:
    def analyze(
        self, mode: AnalysisMode, time_limit_seconds: int | None = None, search_limit: int | None = None
    ) -> AnalysisResult: ...
    def apply_move(self, move_uci: str) -> None: ...
    @property
    def fen(self) -> str: ...
    @property
    def moves_uci(self) -> list[str]: ...
    @property
    def root_visits(self) -> int: ...
    @property
    def starting_fen(self) -> str: ...

class ChessPosition:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, fen: str) -> None: ...
    def __repr__(self) -> str: ...
    def action_id_from_uci(self, move_uci: str) -> int: ...
    def action_uci(self, action_id: int) -> str: ...
    def approximate_result_score(self) -> float: ...
    def child(self, action_id: int) -> ChessPosition: ...
    def legal_actions(self) -> list[int]: ...
    def packed_encoding(self) -> bytes: ...
    def terminal_value(self) -> float: ...
    @property
    def current_player(self) -> int: ...
    @property
    def fen(self) -> str: ...
    @property
    def is_terminal(self) -> bool: ...

class ChessSearchChild:
    @property
    def encoded_move(self) -> int: ...
    @property
    def is_materialized(self) -> bool: ...
    @property
    def move(self) -> str: ...
    @property
    def policy(self) -> float: ...
    @property
    def raw_policy(self) -> float: ...
    @property
    def result_sum(self) -> float: ...
    @property
    def virtual_loss(self) -> float: ...
    @property
    def visits(self) -> int: ...

class ChessSearchRoot:
    def __repr__(self) -> str: ...
    def discount(self, retained_fraction: float) -> None: ...
    def make_new_root(self, child_index: int) -> ChessSearchRoot: ...
    def play(self, action_id: int) -> None: ...
    def reset(self) -> None: ...
    @property
    def arena_capacity(self) -> int: ...
    @property
    def children(self) -> list[ChessSearchChild]: ...
    @property
    def fen(self) -> str: ...
    @property
    def is_expanded(self) -> bool: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def max_depth(self) -> int: ...
    @property
    def position(self) -> ChessPosition: ...
    @property
    def repetition_count(self) -> int: ...
    @property
    def result_sum(self) -> float: ...
    @property
    def total_child_records(self) -> int: ...
    @property
    def virtual_loss(self) -> float: ...
    @property
    def visits(self) -> int: ...

class ChessSelfPlaySearch:
    @staticmethod
    def inference_dimensions() -> InferenceDimensions: ...
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_generation: int = 0,
    ) -> None: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def inference_with_history(
        self, histories: list[tuple[str, list[str]]]
    ) -> list[tuple[list[tuple[int, float]], float]]: ...
    def new_root(self, position: ChessPosition, maximum_capacity: int = 0) -> ChessSearchRoot: ...
    def new_root_with_history(self, starting_fen: str, moves_uci: list[str]) -> ChessSearchRoot: ...
    def refresh_model(self, model_generation: int, model_path: str) -> None: ...
    def request(
        self,
        root: ChessSearchRoot,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> ChessSelfPlaySearchRequest: ...
    def reset_spend_residual(self) -> None: ...
    def search(
        self, requests: list[ChessSelfPlaySearchRequest], collect_statistics: bool = False
    ) -> ChessSelfPlaySearchBatch: ...
    def update_search_schedule(self, search_parameters: SelfPlaySearchParameters) -> bool: ...
    @property
    def arena_capacity(self) -> int: ...
    @property
    def model_generation(self) -> int: ...
    @property
    def model_version(self) -> int: ...
    @property
    def spend_residual(self) -> int: ...

class ChessSelfPlaySearchBatch:
    @property
    def results(self) -> list[ChessSelfPlaySearchResult]: ...
    @property
    def simulations_completed(self) -> int: ...
    @property
    def statistics(self) -> SelfPlaySearchStatistics: ...

class ChessSelfPlaySearchRequest:
    def __init__(
        self,
        root: ChessSearchRoot,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> None: ...
    @property
    def add_root_noise(self) -> bool: ...
    @property
    def assigned_additional_visits(self) -> int | None: ...
    @property
    def checkpoint_detail(self) -> SearchCheckpointDetail: ...
    @property
    def force_root_playouts(self) -> bool: ...
    @property
    def parallel_searches(self) -> int | None: ...
    @property
    def policy_checkpoint_visits(self) -> list[int]: ...
    @property
    def root(self) -> ChessSearchRoot: ...

class ChessSelfPlaySearchResult:
    @property
    def assigned_additional_visits(self) -> int: ...
    @property
    def checkpoints(self) -> list[SearchCheckpoint]: ...
    @property
    def final_visits(self) -> int: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def network_root_value(self) -> float: ...
    @property
    def parallel_searches(self) -> int: ...
    @property
    def policy_correction(self) -> float: ...
    @property
    def policy_target_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...
    @property
    def predicted_search_budget(self) -> float: ...
    @property
    def root(self) -> ChessSearchRoot: ...
    @property
    def root_value(self) -> float: ...
    @property
    def search_budget_logit(self) -> float: ...
    @property
    def search_visit_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def spend_residual(self) -> int: ...
    @property
    def starting_visits(self) -> int: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def value_correction(self) -> float: ...

class FirstPlayUrgencyKind:
    """
    Members:

      ZERO

      PARENT_VALUE

      REDUCED_PARENT_VALUE
    """

    PARENT_VALUE: typing.ClassVar[FirstPlayUrgencyKind]  # value = <FirstPlayUrgencyKind.PARENT_VALUE: 1>
    REDUCED_PARENT_VALUE: typing.ClassVar[
        FirstPlayUrgencyKind
    ]  # value = <FirstPlayUrgencyKind.REDUCED_PARENT_VALUE: 2>
    ZERO: typing.ClassVar[FirstPlayUrgencyKind]  # value = <FirstPlayUrgencyKind.ZERO: 0>
    __members__: typing.ClassVar[
        dict[str, FirstPlayUrgencyKind]
    ]  # value = {'ZERO': <FirstPlayUrgencyKind.ZERO: 0>, 'PARENT_VALUE': <FirstPlayUrgencyKind.PARENT_VALUE: 1>, 'REDUCED_PARENT_VALUE': <FirstPlayUrgencyKind.REDUCED_PARENT_VALUE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class FirstPlayUrgencyParameters:
    def __init__(self, kind: FirstPlayUrgencyKind, reduction: float = 0.0) -> None: ...
    @property
    def kind(self) -> FirstPlayUrgencyKind: ...
    @property
    def reduction(self) -> float: ...

class FixedSearchLimit:
    def __init__(self, visits: int) -> None: ...
    @property
    def visits(self) -> int: ...

class GameAnalysisResult:
    @property
    def candidates(self) -> list[ActionAnalysisCandidate]: ...
    @property
    def chosen_action_id(self) -> int: ...
    @property
    def elapsed_milliseconds(self) -> int: ...
    @property
    def maximum_depth(self) -> int: ...
    @property
    def outcome(self) -> WdlPrediction | None: ...
    @property
    def principal_variation(self) -> list[int]: ...
    @property
    def searches(self) -> int: ...
    @property
    def value(self) -> float: ...

class GameSearchResult:
    @property
    def assigned_additional_visits(self) -> int: ...
    @property
    def checkpoints(self) -> list[SearchCheckpoint]: ...
    @property
    def final_visits(self) -> int: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def network_root_value(self) -> float: ...
    @property
    def parallel_searches(self) -> int: ...
    @property
    def policy_correction(self) -> float: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...
    @property
    def predicted_search_budget(self) -> float: ...
    @property
    def root_value(self) -> float: ...
    @property
    def search_budget_logit(self) -> float: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def spend_residual(self) -> int: ...
    @property
    def starting_visits(self) -> int: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def value_correction(self) -> float: ...

class GameSearchVisit:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GameSearchVisit) -> bool: ...
    def __init__(self, action_id: int, visit_count: int) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def action_id(self) -> int: ...
    @property
    def visit_count(self) -> int: ...

class GoAnalysis7:
    def __init__(self, runtime_parameters: InferenceConfiguration, parameters: AnalysisParameters) -> None: ...
    def analyze_counted(self, root: GoSearchRoot7, searches: int) -> GameAnalysisResult: ...
    def analyze_policy(self, root: GoSearchRoot7) -> GameAnalysisResult: ...
    def analyze_timed(self, root: GoSearchRoot7, seconds: int) -> GameAnalysisResult: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def new_root(self, rules: GoRules) -> GoSearchRoot7: ...

class GoAnalysis9:
    def __init__(self, runtime_parameters: InferenceConfiguration, parameters: AnalysisParameters) -> None: ...
    def analyze_counted(self, root: GoSearchRoot9, searches: int) -> GameAnalysisResult: ...
    def analyze_policy(self, root: GoSearchRoot9) -> GameAnalysisResult: ...
    def analyze_timed(self, root: GoSearchRoot9, seconds: int) -> GameAnalysisResult: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def new_root(self, rules: GoRules) -> GoSearchRoot9: ...

class GoAreaScore:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GoAreaScore) -> bool: ...
    @property
    def black_half_points(self) -> int: ...
    @property
    def white_half_points(self) -> int: ...
    @property
    def winner(self) -> GoPlayer | None: ...

class GoPlayer:
    """
    Members:

      BLACK

      WHITE
    """

    BLACK: typing.ClassVar[GoPlayer]  # value = <GoPlayer.BLACK: 1>
    WHITE: typing.ClassVar[GoPlayer]  # value = <GoPlayer.WHITE: 2>
    __members__: typing.ClassVar[
        dict[str, GoPlayer]
    ]  # value = {'BLACK': <GoPlayer.BLACK: 1>, 'WHITE': <GoPlayer.WHITE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GoPosition7:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def restore(
        black_history: list[list[int]],
        white_history: list[list[int]],
        player: GoPlayer,
        ko_point: int | None,
        consecutive_passes: int,
        move_number: int,
        rules: GoRules,
    ) -> GoPosition7: ...
    def __eq__(self, arg0: GoPosition7) -> bool: ...
    def __init__(self, arg0: GoRules) -> None: ...
    def area_score(self) -> GoAreaScore: ...
    def black_points(self, arg0: int) -> list[int]: ...
    def child(self, arg0: int) -> GoPosition7: ...
    def is_legal(self, arg0: int) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def packed_encoding(self) -> bytes: ...
    def state_hash(self) -> int: ...
    def tensor_encoding(self) -> list[int]: ...
    def terminal_result(self) -> GoTerminalResult: ...
    def terminal_value(self) -> float: ...
    def white_points(self, arg0: int) -> list[int]: ...
    @property
    def board_size(self) -> int: ...
    @property
    def consecutive_passes(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def ko_point(self) -> int | None: ...
    @property
    def move_number(self) -> int: ...
    @property
    def player(self) -> GoPlayer: ...
    @property
    def rules(self) -> GoRules: ...
    @property
    def termination_reason(self) -> GoTerminationReason: ...

class GoPosition9:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def restore(
        black_history: list[list[int]],
        white_history: list[list[int]],
        player: GoPlayer,
        ko_point: int | None,
        consecutive_passes: int,
        move_number: int,
        rules: GoRules,
    ) -> GoPosition9: ...
    def __eq__(self, arg0: GoPosition9) -> bool: ...
    def __init__(self, arg0: GoRules) -> None: ...
    def area_score(self) -> GoAreaScore: ...
    def black_points(self, arg0: int) -> list[int]: ...
    def child(self, arg0: int) -> GoPosition9: ...
    def is_legal(self, arg0: int) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def packed_encoding(self) -> bytes: ...
    def state_hash(self) -> int: ...
    def tensor_encoding(self) -> list[int]: ...
    def terminal_result(self) -> GoTerminalResult: ...
    def terminal_value(self) -> float: ...
    def white_points(self, arg0: int) -> list[int]: ...
    @property
    def board_size(self) -> int: ...
    @property
    def consecutive_passes(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def ko_point(self) -> int | None: ...
    @property
    def move_number(self) -> int: ...
    @property
    def player(self) -> GoPlayer: ...
    @property
    def rules(self) -> GoRules: ...
    @property
    def termination_reason(self) -> GoTerminationReason: ...

class GoRules:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GoRules) -> bool: ...
    def __init__(self, komi_half_points: int, maximum_moves: int) -> None: ...
    @property
    def komi_half_points(self) -> int: ...
    @property
    def maximum_moves(self) -> int: ...

class GoSearchRoot7:
    def discount(self, retained_fraction: float) -> None: ...
    def play(self, action_id: int) -> None: ...
    def reset(self) -> None: ...
    @property
    def children(self) -> list[tuple[int, int]]: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def position(self) -> GoPosition7: ...
    @property
    def visits(self) -> int: ...

class GoSearchRoot9:
    def discount(self, retained_fraction: float) -> None: ...
    def play(self, action_id: int) -> None: ...
    def reset(self) -> None: ...
    @property
    def children(self) -> list[tuple[int, int]]: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def live_nodes(self) -> int: ...
    @property
    def position(self) -> GoPosition9: ...
    @property
    def visits(self) -> int: ...

class GoSelfPlaySearch7:
    @staticmethod
    def inference_dimensions() -> InferenceDimensions: ...
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_generation: int = 0,
    ) -> None: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def new_root(self, position: GoPosition7, maximum_capacity: int = 0) -> GoSearchRoot7: ...
    def refresh_model(self, model_generation: int, model_path: str) -> None: ...
    def request(
        self,
        root: GoSearchRoot7,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> GoSelfPlaySearchRequest7: ...
    def reset_spend_residual(self) -> None: ...
    def search(
        self, requests: list[GoSelfPlaySearchRequest7], collect_statistics: bool = False
    ) -> GoSelfPlaySearchBatch7: ...
    def update_search_schedule(self, search_parameters: SelfPlaySearchParameters) -> bool: ...
    @property
    def model_generation(self) -> int: ...
    @property
    def spend_residual(self) -> int: ...

class GoSelfPlaySearch9:
    @staticmethod
    def inference_dimensions() -> InferenceDimensions: ...
    def __init__(
        self,
        runtime_parameters: InferenceConfiguration,
        search_parameters: SelfPlaySearchParameters,
        inference_parameters: BatchedInferenceParameters,
        initial_model_generation: int = 0,
    ) -> None: ...
    def inference_statistics(self) -> InferenceStatistics: ...
    def new_root(self, position: GoPosition9, maximum_capacity: int = 0) -> GoSearchRoot9: ...
    def refresh_model(self, model_generation: int, model_path: str) -> None: ...
    def request(
        self,
        root: GoSearchRoot9,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> GoSelfPlaySearchRequest9: ...
    def reset_spend_residual(self) -> None: ...
    def search(
        self, requests: list[GoSelfPlaySearchRequest9], collect_statistics: bool = False
    ) -> GoSelfPlaySearchBatch9: ...
    def update_search_schedule(self, search_parameters: SelfPlaySearchParameters) -> bool: ...
    @property
    def model_generation(self) -> int: ...
    @property
    def spend_residual(self) -> int: ...

class GoSelfPlaySearchBatch7:
    @property
    def results(self) -> list[GoSelfPlaySearchResult7]: ...
    @property
    def simulations_completed(self) -> int: ...
    @property
    def statistics(self) -> SelfPlaySearchStatistics: ...

class GoSelfPlaySearchBatch9:
    @property
    def results(self) -> list[GoSelfPlaySearchResult9]: ...
    @property
    def simulations_completed(self) -> int: ...
    @property
    def statistics(self) -> SelfPlaySearchStatistics: ...

class GoSelfPlaySearchRequest7:
    def __init__(
        self,
        root: GoSearchRoot7,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> None: ...
    @property
    def add_root_noise(self) -> bool: ...
    @property
    def assigned_additional_visits(self) -> int | None: ...
    @property
    def checkpoint_detail(self) -> SearchCheckpointDetail: ...
    @property
    def force_root_playouts(self) -> bool: ...
    @property
    def parallel_searches(self) -> int | None: ...
    @property
    def policy_checkpoint_visits(self) -> list[int]: ...
    @property
    def root(self) -> GoSearchRoot7: ...

class GoSelfPlaySearchRequest9:
    def __init__(
        self,
        root: GoSearchRoot9,
        assigned_additional_visits: int | None = None,
        policy_checkpoint_visits: list[int] = [],
        parallel_searches: int | None = None,
        add_root_noise: bool = True,
        force_root_playouts: bool = True,
        checkpoint_detail: SearchCheckpointDetail = ...,
    ) -> None: ...
    @property
    def add_root_noise(self) -> bool: ...
    @property
    def assigned_additional_visits(self) -> int | None: ...
    @property
    def checkpoint_detail(self) -> SearchCheckpointDetail: ...
    @property
    def force_root_playouts(self) -> bool: ...
    @property
    def parallel_searches(self) -> int | None: ...
    @property
    def policy_checkpoint_visits(self) -> list[int]: ...
    @property
    def root(self) -> GoSearchRoot9: ...

class GoSelfPlaySearchResult7:
    @property
    def assigned_additional_visits(self) -> int: ...
    @property
    def checkpoints(self) -> list[SearchCheckpoint]: ...
    @property
    def final_visits(self) -> int: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def network_root_value(self) -> float: ...
    @property
    def parallel_searches(self) -> int: ...
    @property
    def policy_correction(self) -> float: ...
    @property
    def policy_target_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...
    @property
    def predicted_search_budget(self) -> float: ...
    @property
    def root(self) -> GoSearchRoot7: ...
    @property
    def root_value(self) -> float: ...
    @property
    def search_budget_logit(self) -> float: ...
    @property
    def search_visit_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def spend_residual(self) -> int: ...
    @property
    def starting_visits(self) -> int: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def value_correction(self) -> float: ...

class GoSelfPlaySearchResult9:
    @property
    def assigned_additional_visits(self) -> int: ...
    @property
    def checkpoints(self) -> list[SearchCheckpoint]: ...
    @property
    def final_visits(self) -> int: ...
    @property
    def highest_visited_child_action_id(self) -> int: ...
    @property
    def highest_visited_child_q(self) -> float: ...
    @property
    def highest_visited_child_visit_count(self) -> int: ...
    @property
    def network_root_value(self) -> float: ...
    @property
    def parallel_searches(self) -> int: ...
    @property
    def policy_correction(self) -> float: ...
    @property
    def policy_target_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...
    @property
    def predicted_search_budget(self) -> float: ...
    @property
    def root(self) -> GoSearchRoot9: ...
    @property
    def root_value(self) -> float: ...
    @property
    def search_budget_logit(self) -> float: ...
    @property
    def search_visit_columns(self) -> tuple[list[int], list[int]]: ...
    @property
    def search_visits(self) -> list[GameSearchVisit]: ...
    @property
    def spend_residual(self) -> int: ...
    @property
    def starting_visits(self) -> int: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def value_correction(self) -> float: ...

class GoTerminalResult:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GoTerminalResult) -> bool: ...
    @property
    def reason(self) -> GoTerminationReason: ...
    @property
    def score(self) -> GoAreaScore: ...
    @property
    def winner(self) -> GoPlayer | None: ...

class GoTerminationReason:
    """
    Members:

      ONGOING

      TWO_PASSES

      MAXIMUM_MOVES
    """

    MAXIMUM_MOVES: typing.ClassVar[GoTerminationReason]  # value = <GoTerminationReason.MAXIMUM_MOVES: 2>
    ONGOING: typing.ClassVar[GoTerminationReason]  # value = <GoTerminationReason.ONGOING: 0>
    TWO_PASSES: typing.ClassVar[GoTerminationReason]  # value = <GoTerminationReason.TWO_PASSES: 1>
    __members__: typing.ClassVar[
        dict[str, GoTerminationReason]
    ]  # value = {'ONGOING': <GoTerminationReason.ONGOING: 0>, 'TWO_PASSES': <GoTerminationReason.TWO_PASSES: 1>, 'MAXIMUM_MOVES': <GoTerminationReason.MAXIMUM_MOVES: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InferenceConfiguration:
    device: InferenceDevice
    device_id: int
    execution_options: InferenceExecutionOptions
    model_path: str
    sdpa_backend: SdpaBackend
    def __init__(
        self,
        device_id: int,
        model_path: str,
        device: InferenceDevice = ...,
        execution_options: InferenceExecutionOptions = ...,
    ) -> None: ...

class InferenceDevice:
    """
    Members:

      AUTO

      CPU

      CUDA
    """

    AUTO: typing.ClassVar[InferenceDevice]  # value = <InferenceDevice.AUTO: 0>
    CPU: typing.ClassVar[InferenceDevice]  # value = <InferenceDevice.CPU: 1>
    CUDA: typing.ClassVar[InferenceDevice]  # value = <InferenceDevice.CUDA: 2>
    __members__: typing.ClassVar[
        dict[str, InferenceDevice]
    ]  # value = {'AUTO': <InferenceDevice.AUTO: 0>, 'CPU': <InferenceDevice.CPU: 1>, 'CUDA': <InferenceDevice.CUDA: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InferenceDimensions:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: InferenceDimensions) -> bool: ...
    def __init__(self, channels: int, rows: int, columns: int, actions: int, outcomes: int) -> None: ...
    @property
    def actions(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def columns(self) -> int: ...
    @property
    def outcomes(self) -> int: ...
    @property
    def rows(self) -> int: ...

class InferenceExecutionOptions:
    cudnn_benchmark: bool
    memory_format: InferenceMemoryFormat
    precision: InferencePrecision
    sdpa_backend: SdpaBackend
    def __init__(
        self,
        sdpa_backend: SdpaBackend = ...,
        precision: InferencePrecision = ...,
        memory_format: InferenceMemoryFormat = ...,
        cudnn_benchmark: bool = False,
    ) -> None: ...

class InferenceMemoryFormat:
    """
    Members:

      CONTIGUOUS

      CHANNELS_LAST
    """

    CHANNELS_LAST: typing.ClassVar[InferenceMemoryFormat]  # value = <InferenceMemoryFormat.CHANNELS_LAST: 1>
    CONTIGUOUS: typing.ClassVar[InferenceMemoryFormat]  # value = <InferenceMemoryFormat.CONTIGUOUS: 0>
    __members__: typing.ClassVar[
        dict[str, InferenceMemoryFormat]
    ]  # value = {'CONTIGUOUS': <InferenceMemoryFormat.CONTIGUOUS: 0>, 'CHANNELS_LAST': <InferenceMemoryFormat.CHANNELS_LAST: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InferencePrecision:
    """
    Members:

      BFLOAT16

      FLOAT16

      FLOAT32
    """

    BFLOAT16: typing.ClassVar[InferencePrecision]  # value = <InferencePrecision.BFLOAT16: 0>
    FLOAT16: typing.ClassVar[InferencePrecision]  # value = <InferencePrecision.FLOAT16: 1>
    FLOAT32: typing.ClassVar[InferencePrecision]  # value = <InferencePrecision.FLOAT32: 2>
    __members__: typing.ClassVar[
        dict[str, InferencePrecision]
    ]  # value = {'BFLOAT16': <InferencePrecision.BFLOAT16: 0>, 'FLOAT16': <InferencePrecision.FLOAT16: 1>, 'FLOAT32': <InferencePrecision.FLOAT32: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InferenceStatistics:
    def __init__(self) -> None: ...
    @property
    def averageNumberOfPositionsInInferenceCall(self) -> float: ...
    @property
    def boardEncodingNanoseconds(self) -> int: ...
    @property
    def evaluations(self) -> int: ...
    @property
    def inferenceNanoseconds(self) -> int: ...
    @property
    def modelBatchSizeHistogram(self) -> list[int]: ...
    @property
    def modelInferenceCalls(self) -> int: ...
    @property
    def modelInferencePositions(self) -> int: ...
    @property
    def resultProcessingNanoseconds(self) -> int: ...
    @property
    def treeBackupNanoseconds(self) -> int: ...
    @property
    def treeOwnerWaitNanoseconds(self) -> int: ...
    @property
    def treeSelectionNanoseconds(self) -> int: ...
    @property
    def workerUtilization(self) -> float: ...

class PredictedSearchBudgetLimit:
    def __init__(self, baseline_visits: int, curve: SearchBudgetCurve) -> None: ...
    @property
    def baseline_visits(self) -> int: ...
    @property
    def curve(self) -> SearchBudgetCurve: ...

class SdpaBackend:
    """
    Members:

      AUTOMATIC

      FLASH

      MEMORY_EFFICIENT

      MATH

      CUDNN
    """

    AUTOMATIC: typing.ClassVar[SdpaBackend]  # value = <SdpaBackend.AUTOMATIC: 0>
    CUDNN: typing.ClassVar[SdpaBackend]  # value = <SdpaBackend.CUDNN: 4>
    FLASH: typing.ClassVar[SdpaBackend]  # value = <SdpaBackend.FLASH: 1>
    MATH: typing.ClassVar[SdpaBackend]  # value = <SdpaBackend.MATH: 3>
    MEMORY_EFFICIENT: typing.ClassVar[SdpaBackend]  # value = <SdpaBackend.MEMORY_EFFICIENT: 2>
    __members__: typing.ClassVar[
        dict[str, SdpaBackend]
    ]  # value = {'AUTOMATIC': <SdpaBackend.AUTOMATIC: 0>, 'FLASH': <SdpaBackend.FLASH: 1>, 'MEMORY_EFFICIENT': <SdpaBackend.MEMORY_EFFICIENT: 2>, 'MATH': <SdpaBackend.MATH: 3>, 'CUDNN': <SdpaBackend.CUDNN: 4>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SearchBudgetCurve:
    def __init__(
        self, multipliers: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(10)]
    ) -> None: ...
    def multiplier(self, quantile: float) -> float: ...
    @property
    def multipliers(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(10)]: ...

class SearchCheckpoint:
    @property
    def policy_target_visits(self) -> list[GameSearchVisit]: ...
    @property
    def visits(self) -> int: ...

class SearchCheckpointDetail:
    """
    Members:

      SCALARS

      POLICIES
    """

    POLICIES: typing.ClassVar[SearchCheckpointDetail]  # value = <SearchCheckpointDetail.POLICIES: 1>
    SCALARS: typing.ClassVar[SearchCheckpointDetail]  # value = <SearchCheckpointDetail.SCALARS: 0>
    __members__: typing.ClassVar[
        dict[str, SearchCheckpointDetail]
    ]  # value = {'SCALARS': <SearchCheckpointDetail.SCALARS: 0>, 'POLICIES': <SearchCheckpointDetail.POLICIES: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SearchStopReason:
    """
    Members:

      FIXED_LIMIT

      ADDITIONAL_VISITS

      PREDICTED_BUDGET
    """

    ADDITIONAL_VISITS: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.ADDITIONAL_VISITS: 1>
    FIXED_LIMIT: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.FIXED_LIMIT: 0>
    PREDICTED_BUDGET: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.PREDICTED_BUDGET: 2>
    __members__: typing.ClassVar[
        dict[str, SearchStopReason]
    ]  # value = {'FIXED_LIMIT': <SearchStopReason.FIXED_LIMIT: 0>, 'ADDITIONAL_VISITS': <SearchStopReason.ADDITIONAL_VISITS: 1>, 'PREDICTED_BUDGET': <SearchStopReason.PREDICTED_BUDGET: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SelfPlaySearchParameters:
    baseline_visits: int
    dirichlet_alpha: float
    dirichlet_epsilon: float
    search_budget_curve: SearchBudgetCurve
    tree_search: TreeSearchParameters
    def __init__(
        self,
        baseline_visits: int,
        search_budget_curve: SearchBudgetCurve,
        tree_search: TreeSearchParameters,
        dirichlet_alpha: float,
        dirichlet_epsilon: float,
    ) -> None: ...

class SelfPlaySearchStatistics:
    @property
    def average_depth(self) -> float: ...
    @property
    def average_entropy(self) -> float: ...
    @property
    def average_kl_divergence(self) -> float: ...
    @property
    def average_policy_search_kl_divergence(self) -> float: ...
    @property
    def selected_action_prior_rank(self) -> float: ...
    @property
    def top_action_disagreement(self) -> float: ...

class TreeSearchParameters:
    def __init__(
        self,
        exploration_constant: float,
        first_play_urgency: FirstPlayUrgencyParameters,
        forced_playout_coefficient: float,
        value_discount_per_ply: float,
        virtual_loss_weight: float = 1.0,
    ) -> None: ...
    @property
    def exploration_constant(self) -> float: ...
    @property
    def first_play_urgency(self) -> FirstPlayUrgencyParameters: ...
    @property
    def forced_playout_coefficient(self) -> float: ...
    @property
    def value_discount_per_ply(self) -> float: ...
    @property
    def virtual_loss_weight(self) -> float: ...

class WdlPrediction:
    @property
    def draw(self) -> float: ...
    @property
    def loss(self) -> float: ...
    @property
    def value(self) -> float: ...
    @property
    def win(self) -> float: ...

def encode_board_packed_bytes(fen: str) -> bytes:
    """
    Encode a FEN into the canonical packed plane-major byte layout.
    """

def mirror_chess_action_id(action_id: int) -> int: ...
def new_root(fen: str, arena_capacity: int) -> ChessSearchRoot: ...
def new_root_with_history(starting_fen: str, moves_uci: list[str], arena_capacity: int) -> ChessSearchRoot: ...
def search_budget_multiplier(curve: SearchBudgetCurve, quantile: float) -> float: ...
def search_parallelism(additional_visits: int) -> int: ...

CHESS_ACTION_SIZE: int = 1880
OutcomeProbabilities = WdlPrediction
