"""
Typed native Go correctness core
"""

from __future__ import annotations
import typing

__all__ = [
    'AdaptiveStoppingConfiguration',
    'AreaScore',
    'Coordinate',
    'FixedPuctConfiguration',
    'FpuPolicy',
    'GoEncoding',
    'GoInferenceRequest',
    'GoRules',
    'GoState',
    'InferenceResult',
    'MAXIMUM_HISTORY_LENGTH',
    'MAXIMUM_SIMULATION_COUNT',
    'Player',
    'PrefixTraceConfiguration',
    'RootChildStatistics',
    'RootNoiseConfiguration',
    'SearchBudgetClass',
    'SearchResult',
    'SearchStopReason',
    'SearchTelemetry',
    'SearchTraceSnapshot',
    'Stone',
    'Symmetry',
    'TerminalResult',
    'TerminationReason',
    'inverse_symmetry',
    'search_go_fixed',
    'transform_action',
    'transform_coordinate',
    'transform_encoding',
]

class AdaptiveStoppingConfiguration:
    def __init__(
        self,
        enabled: bool,
        minimum_simulations: int,
        check_interval_simulations: int,
        required_top_visit_fraction: float,
        required_top_two_margin: float,
    ) -> None: ...
    @property
    def check_interval_simulations(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def minimum_simulations(self) -> int: ...
    @property
    def required_top_two_margin(self) -> float: ...
    @property
    def required_top_visit_fraction(self) -> float: ...

class AreaScore:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: AreaScore) -> bool: ...
    @property
    def black_twice(self) -> int: ...
    @property
    def white_twice(self) -> int: ...
    @property
    def winner(self) -> Player | None: ...

class Coordinate:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Coordinate) -> bool: ...
    @property
    def column(self) -> int: ...
    @property
    def row(self) -> int: ...

class FixedPuctConfiguration:
    @typing.overload
    def __init__(
        self,
        simulation_cap: int,
        exploration_constant: float,
        backup_discount: float,
        no_visited_child_value: float,
        action_temperature: float,
        root_noise_seed: int,
        action_sampling_seed: int,
        root_noise: RootNoiseConfiguration,
        tree_reuse: bool,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        simulation_cap: int,
        exploration_constant: float,
        backup_discount: float,
        no_visited_child_value: float,
        action_temperature: float,
        root_noise_seed: int,
        action_sampling_seed: int,
        root_noise: RootNoiseConfiguration,
        tree_reuse: bool,
        fpu_policy: FpuPolicy,
        fpu_reduction: float,
        adaptive_stopping: AdaptiveStoppingConfiguration,
        budget_class: SearchBudgetClass,
        policy_target_weight: float,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        simulation_cap: int,
        exploration_constant: float,
        backup_discount: float,
        no_visited_child_value: float,
        action_temperature: float,
        root_noise_seed: int,
        action_sampling_seed: int,
        root_noise: RootNoiseConfiguration,
        tree_reuse: bool,
        fpu_policy: FpuPolicy,
        fpu_reduction: float,
        adaptive_stopping: AdaptiveStoppingConfiguration,
        budget_class: SearchBudgetClass,
        policy_target_weight: float,
        prefix_trace: PrefixTraceConfiguration,
    ) -> None: ...
    @property
    def action_sampling_seed(self) -> int: ...
    @property
    def action_temperature(self) -> float: ...
    @property
    def adaptive_stopping(self) -> AdaptiveStoppingConfiguration: ...
    @property
    def backup_discount(self) -> float: ...
    @property
    def budget_class(self) -> SearchBudgetClass: ...
    @property
    def exploration_constant(self) -> float: ...
    @property
    def fpu_policy(self) -> FpuPolicy: ...
    @property
    def fpu_reduction(self) -> float: ...
    @property
    def no_visited_child_value(self) -> float: ...
    @property
    def policy_target_weight(self) -> float: ...
    @property
    def prefix_trace(self) -> PrefixTraceConfiguration: ...
    @property
    def root_noise(self) -> RootNoiseConfiguration: ...
    @property
    def root_noise_seed(self) -> int: ...
    @property
    def simulation_cap(self) -> int: ...
    @property
    def tree_reuse(self) -> bool: ...

class FpuPolicy:
    """
    Members:

      PARENT_VALUE

      REDUCED_PARENT_VALUE

      VISITED_CHILD_MEAN
    """

    PARENT_VALUE: typing.ClassVar[FpuPolicy]  # value = <FpuPolicy.PARENT_VALUE: 0>
    REDUCED_PARENT_VALUE: typing.ClassVar[FpuPolicy]  # value = <FpuPolicy.REDUCED_PARENT_VALUE: 1>
    VISITED_CHILD_MEAN: typing.ClassVar[FpuPolicy]  # value = <FpuPolicy.VISITED_CHILD_MEAN: 2>
    __members__: typing.ClassVar[
        dict[str, FpuPolicy]
    ]  # value = {'PARENT_VALUE': <FpuPolicy.PARENT_VALUE: 0>, 'REDUCED_PARENT_VALUE': <FpuPolicy.REDUCED_PARENT_VALUE: 1>, 'VISITED_CHILD_MEAN': <FpuPolicy.VISITED_CHILD_MEAN: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GoEncoding:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GoEncoding) -> bool: ...
    def at(self, arg0: int, arg1: int, arg2: int) -> int: ...
    @property
    def board_size(self) -> int: ...
    @property
    def planes(self) -> int: ...
    @property
    def values(self) -> list[int]: ...

class GoInferenceRequest:
    @property
    def action_count(self) -> int: ...
    @property
    def encoding(self) -> GoEncoding: ...
    @property
    def request_id(self) -> int: ...

class GoRules:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GoRules) -> bool: ...
    def __init__(self, board_size: int, komi_half_points: int, safety_ply_cap: int, history_length: int) -> None: ...
    @property
    def board_size(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    @property
    def komi_half_points(self) -> int: ...
    @property
    def safety_ply_cap(self) -> int: ...

class GoState:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def restore(
        rules: GoRules,
        board: list[Stone],
        current_player: Player,
        ply: int,
        consecutive_passes: int,
        position_history: list[list[Stone]],
    ) -> GoState: ...
    def __eq__(self, arg0: GoState) -> bool: ...
    def __init__(self, arg0: GoRules) -> None: ...
    def apply(self, arg0: int) -> None: ...
    def area_score(self) -> AreaScore: ...
    def canonical_encoding(self) -> GoEncoding: ...
    def copy(self) -> GoState: ...
    def is_legal(self, arg0: int) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def state_hash(self) -> int: ...
    def terminal_result(self) -> TerminalResult: ...
    @property
    def action_count(self) -> int: ...
    @property
    def board(self) -> list[Stone]: ...
    @property
    def board_size(self) -> int: ...
    @property
    def consecutive_passes(self) -> int: ...
    @property
    def current_player(self) -> Player: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def pass_action(self) -> int: ...
    @property
    def ply(self) -> int: ...
    @property
    def rules(self) -> GoRules: ...
    @property
    def termination_reason(self) -> TerminationReason: ...

class InferenceResult:
    def __init__(self, request_id: int, policy: list[float], value: float) -> None: ...
    @property
    def policy(self) -> list[float]: ...
    @property
    def request_id(self) -> int: ...
    @property
    def value(self) -> float: ...

class Player:
    """
    Members:

      BLACK

      WHITE
    """

    BLACK: typing.ClassVar[Player]  # value = <Player.BLACK: 1>
    WHITE: typing.ClassVar[Player]  # value = <Player.WHITE: 2>
    __members__: typing.ClassVar[dict[str, Player]]  # value = {'BLACK': <Player.BLACK: 1>, 'WHITE': <Player.WHITE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PrefixTraceConfiguration:
    def __init__(self, enabled: bool, checkpoints: list[int]) -> None: ...
    @property
    def checkpoints(self) -> list[int]: ...
    @property
    def enabled(self) -> bool: ...

class RootChildStatistics:
    @property
    def action(self) -> int: ...
    @property
    def action_value(self) -> float: ...
    @property
    def prior(self) -> float: ...
    @property
    def visits(self) -> int: ...

class RootNoiseConfiguration:
    def __init__(self, enabled: bool, alpha: float, fraction: float) -> None: ...
    @property
    def alpha(self) -> float: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def fraction(self) -> float: ...

class SearchBudgetClass:
    """
    Members:

      FIXED

      PROGRESSIVE_STAGE

      MIXED_FAST

      MIXED_FULL
    """

    FIXED: typing.ClassVar[SearchBudgetClass]  # value = <SearchBudgetClass.FIXED: 0>
    MIXED_FAST: typing.ClassVar[SearchBudgetClass]  # value = <SearchBudgetClass.MIXED_FAST: 2>
    MIXED_FULL: typing.ClassVar[SearchBudgetClass]  # value = <SearchBudgetClass.MIXED_FULL: 3>
    PROGRESSIVE_STAGE: typing.ClassVar[SearchBudgetClass]  # value = <SearchBudgetClass.PROGRESSIVE_STAGE: 1>
    __members__: typing.ClassVar[
        dict[str, SearchBudgetClass]
    ]  # value = {'FIXED': <SearchBudgetClass.FIXED: 0>, 'PROGRESSIVE_STAGE': <SearchBudgetClass.PROGRESSIVE_STAGE: 1>, 'MIXED_FAST': <SearchBudgetClass.MIXED_FAST: 2>, 'MIXED_FULL': <SearchBudgetClass.MIXED_FULL: 3>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SearchResult:
    @property
    def prefix_trace(self) -> list[SearchTraceSnapshot]: ...
    @property
    def root_children(self) -> list[RootChildStatistics]: ...
    @property
    def root_policy(self) -> list[float]: ...
    @property
    def root_value(self) -> float | None: ...
    @property
    def root_visits(self) -> list[int]: ...
    @property
    def selected_action(self) -> int | None: ...
    @property
    def telemetry(self) -> SearchTelemetry: ...

class SearchStopReason:
    """
    Members:

      FULL_BUDGET

      TERMINAL_ROOT

      ADAPTIVE_CONFIDENCE
    """

    ADAPTIVE_CONFIDENCE: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.ADAPTIVE_CONFIDENCE: 2>
    FULL_BUDGET: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.FULL_BUDGET: 0>
    TERMINAL_ROOT: typing.ClassVar[SearchStopReason]  # value = <SearchStopReason.TERMINAL_ROOT: 1>
    __members__: typing.ClassVar[
        dict[str, SearchStopReason]
    ]  # value = {'FULL_BUDGET': <SearchStopReason.FULL_BUDGET: 0>, 'TERMINAL_ROOT': <SearchStopReason.TERMINAL_ROOT: 1>, 'ADAPTIVE_CONFIDENCE': <SearchStopReason.ADAPTIVE_CONFIDENCE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SearchTelemetry:
    @property
    def actual_simulations(self) -> int: ...
    @property
    def budget_class(self) -> SearchBudgetClass: ...
    @property
    def configured_cap(self) -> int: ...
    @property
    def initial_root_fpu(self) -> float: ...
    @property
    def leaf_inference_requests(self) -> int: ...
    @property
    def policy_target_eligible(self) -> bool: ...
    @property
    def policy_target_weight(self) -> float: ...
    @property
    def root_entropy(self) -> float: ...
    @property
    def root_inference_requests(self) -> int: ...
    @property
    def root_visit_count(self) -> int: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def top_two_visit_margin(self) -> float: ...
    @property
    def total_inference_requests(self) -> int: ...

class SearchTraceSnapshot:
    @property
    def root_policy(self) -> list[float]: ...
    @property
    def root_value(self) -> float: ...
    @property
    def root_visits(self) -> list[int]: ...
    @property
    def simulations(self) -> int: ...

class Stone:
    """
    Members:

      EMPTY

      BLACK

      WHITE
    """

    BLACK: typing.ClassVar[Stone]  # value = <Stone.BLACK: 1>
    EMPTY: typing.ClassVar[Stone]  # value = <Stone.EMPTY: 0>
    WHITE: typing.ClassVar[Stone]  # value = <Stone.WHITE: 2>
    __members__: typing.ClassVar[
        dict[str, Stone]
    ]  # value = {'EMPTY': <Stone.EMPTY: 0>, 'BLACK': <Stone.BLACK: 1>, 'WHITE': <Stone.WHITE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Symmetry:
    """
    Members:

      IDENTITY

      ROTATE_90

      ROTATE_180

      ROTATE_270

      REFLECT

      REFLECT_ROTATE_90

      REFLECT_ROTATE_180

      REFLECT_ROTATE_270
    """

    IDENTITY: typing.ClassVar[Symmetry]  # value = <Symmetry.IDENTITY: 0>
    REFLECT: typing.ClassVar[Symmetry]  # value = <Symmetry.REFLECT: 4>
    REFLECT_ROTATE_180: typing.ClassVar[Symmetry]  # value = <Symmetry.REFLECT_ROTATE_180: 6>
    REFLECT_ROTATE_270: typing.ClassVar[Symmetry]  # value = <Symmetry.REFLECT_ROTATE_270: 7>
    REFLECT_ROTATE_90: typing.ClassVar[Symmetry]  # value = <Symmetry.REFLECT_ROTATE_90: 5>
    ROTATE_180: typing.ClassVar[Symmetry]  # value = <Symmetry.ROTATE_180: 2>
    ROTATE_270: typing.ClassVar[Symmetry]  # value = <Symmetry.ROTATE_270: 3>
    ROTATE_90: typing.ClassVar[Symmetry]  # value = <Symmetry.ROTATE_90: 1>
    __members__: typing.ClassVar[
        dict[str, Symmetry]
    ]  # value = {'IDENTITY': <Symmetry.IDENTITY: 0>, 'ROTATE_90': <Symmetry.ROTATE_90: 1>, 'ROTATE_180': <Symmetry.ROTATE_180: 2>, 'ROTATE_270': <Symmetry.ROTATE_270: 3>, 'REFLECT': <Symmetry.REFLECT: 4>, 'REFLECT_ROTATE_90': <Symmetry.REFLECT_ROTATE_90: 5>, 'REFLECT_ROTATE_180': <Symmetry.REFLECT_ROTATE_180: 6>, 'REFLECT_ROTATE_270': <Symmetry.REFLECT_ROTATE_270: 7>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TerminalResult:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: TerminalResult) -> bool: ...
    @property
    def reason(self) -> TerminationReason: ...
    @property
    def score(self) -> AreaScore | None: ...
    @property
    def winner(self) -> Player | None: ...

class TerminationReason:
    """
    Members:

      ONGOING

      TWO_PASSES

      SAFETY_PLY_CAP
    """

    ONGOING: typing.ClassVar[TerminationReason]  # value = <TerminationReason.ONGOING: 0>
    SAFETY_PLY_CAP: typing.ClassVar[TerminationReason]  # value = <TerminationReason.SAFETY_PLY_CAP: 2>
    TWO_PASSES: typing.ClassVar[TerminationReason]  # value = <TerminationReason.TWO_PASSES: 1>
    __members__: typing.ClassVar[
        dict[str, TerminationReason]
    ]  # value = {'ONGOING': <TerminationReason.ONGOING: 0>, 'TWO_PASSES': <TerminationReason.TWO_PASSES: 1>, 'SAFETY_PLY_CAP': <TerminationReason.SAFETY_PLY_CAP: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def inverse_symmetry(arg0: Symmetry) -> Symmetry: ...
def search_go_fixed(
    state: GoState, evaluator: typing.Callable, configuration: FixedPuctConfiguration
) -> SearchResult: ...
def transform_action(arg0: int, arg1: int, arg2: Symmetry) -> int: ...
def transform_coordinate(arg0: int, arg1: int, arg2: int, arg3: Symmetry) -> Coordinate: ...
def transform_encoding(arg0: GoEncoding, arg1: Symmetry) -> GoEncoding: ...

MAXIMUM_HISTORY_LENGTH: int = 1024
MAXIMUM_SIMULATION_COUNT: int = 2147483647
