from enum import IntEnum
from typing import Callable

MAXIMUM_HISTORY_LENGTH: int
MAXIMUM_SIMULATION_COUNT: int

class Stone(IntEnum):
    EMPTY: Stone
    BLACK: Stone
    WHITE: Stone

class Player(IntEnum):
    BLACK: Player
    WHITE: Player

class TerminationReason(IntEnum):
    ONGOING: TerminationReason
    TWO_PASSES: TerminationReason
    SAFETY_PLY_CAP: TerminationReason

class Symmetry(IntEnum):
    IDENTITY: Symmetry
    ROTATE_90: Symmetry
    ROTATE_180: Symmetry
    ROTATE_270: Symmetry
    REFLECT: Symmetry
    REFLECT_ROTATE_90: Symmetry
    REFLECT_ROTATE_180: Symmetry
    REFLECT_ROTATE_270: Symmetry

class SearchBudgetClass(IntEnum):
    FIXED: SearchBudgetClass

class SearchStopReason(IntEnum):
    FULL_BUDGET: SearchStopReason
    TERMINAL_ROOT: SearchStopReason

class Coordinate:
    @property
    def row(self) -> int: ...
    @property
    def column(self) -> int: ...

class GoRules:
    def __init__(
        self,
        board_size: int,
        komi_half_points: int,
        safety_ply_cap: int,
        history_length: int,
    ) -> None: ...
    @property
    def board_size(self) -> int: ...
    @property
    def komi_half_points(self) -> int: ...
    @property
    def safety_ply_cap(self) -> int: ...
    @property
    def history_length(self) -> int: ...

class AreaScore:
    @property
    def black_twice(self) -> int: ...
    @property
    def white_twice(self) -> int: ...
    @property
    def winner(self) -> Player | None: ...

class TerminalResult:
    @property
    def reason(self) -> TerminationReason: ...
    @property
    def score(self) -> AreaScore | None: ...
    @property
    def winner(self) -> Player | None: ...

class GoEncoding:
    @property
    def planes(self) -> int: ...
    @property
    def board_size(self) -> int: ...
    @property
    def values(self) -> list[int]: ...
    def at(self, plane: int, row: int, column: int) -> int: ...

class GoState:
    def __init__(self, rules: GoRules) -> None: ...
    @classmethod
    def restore(
        cls,
        rules: GoRules,
        board: list[Stone],
        current_player: Player,
        ply: int,
        consecutive_passes: int,
        position_history: list[list[Stone]],
    ) -> GoState: ...
    @property
    def rules(self) -> GoRules: ...
    @property
    def board_size(self) -> int: ...
    @property
    def action_count(self) -> int: ...
    @property
    def pass_action(self) -> int: ...
    @property
    def current_player(self) -> Player: ...
    @property
    def ply(self) -> int: ...
    @property
    def consecutive_passes(self) -> int: ...
    @property
    def board(self) -> list[Stone]: ...
    def is_legal(self, action: int) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def apply(self, action: int) -> None: ...
    @property
    def termination_reason(self) -> TerminationReason: ...
    @property
    def is_terminal(self) -> bool: ...
    def terminal_result(self) -> TerminalResult: ...
    def area_score(self) -> AreaScore: ...
    def canonical_encoding(self) -> GoEncoding: ...
    def copy(self) -> GoState: ...
    def state_hash(self) -> int: ...

class GoInferenceRequest:
    @property
    def request_id(self) -> int: ...
    @property
    def encoding(self) -> GoEncoding: ...
    @property
    def action_count(self) -> int: ...

class InferenceResult:
    def __init__(self, request_id: int, policy: list[float], value: float) -> None: ...
    @property
    def request_id(self) -> int: ...
    @property
    def policy(self) -> list[float]: ...
    @property
    def value(self) -> float: ...

class RootNoiseConfiguration:
    def __init__(self, enabled: bool, alpha: float, fraction: float) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def alpha(self) -> float: ...
    @property
    def fraction(self) -> float: ...

class FixedPuctConfiguration:
    def __init__(
        self,
        simulation_cap: int,
        exploration_constant: float,
        backup_discount: float,
        no_visited_child_value: float,
        action_temperature: float,
        seed: int,
        root_noise: RootNoiseConfiguration,
        tree_reuse: bool,
    ) -> None: ...
    @property
    def simulation_cap(self) -> int: ...
    @property
    def exploration_constant(self) -> float: ...
    @property
    def backup_discount(self) -> float: ...
    @property
    def no_visited_child_value(self) -> float: ...
    @property
    def action_temperature(self) -> float: ...
    @property
    def seed(self) -> int: ...
    @property
    def root_noise(self) -> RootNoiseConfiguration: ...
    @property
    def tree_reuse(self) -> bool: ...

class RootChildStatistics:
    @property
    def action(self) -> int: ...
    @property
    def prior(self) -> float: ...
    @property
    def visits(self) -> int: ...
    @property
    def action_value(self) -> float: ...

class SearchTelemetry:
    @property
    def configured_cap(self) -> int: ...
    @property
    def actual_simulations(self) -> int: ...
    @property
    def budget_class(self) -> SearchBudgetClass: ...
    @property
    def stop_reason(self) -> SearchStopReason: ...
    @property
    def policy_target_eligible(self) -> bool: ...
    @property
    def policy_target_weight(self) -> float: ...
    @property
    def root_visit_count(self) -> int: ...
    @property
    def root_inference_requests(self) -> int: ...
    @property
    def leaf_inference_requests(self) -> int: ...
    @property
    def total_inference_requests(self) -> int: ...
    @property
    def root_entropy(self) -> float: ...
    @property
    def top_two_visit_margin(self) -> float: ...

class SearchResult:
    @property
    def selected_action(self) -> int | None: ...
    @property
    def root_policy(self) -> list[float]: ...
    @property
    def root_visits(self) -> list[int]: ...
    @property
    def root_value(self) -> float | None: ...
    @property
    def root_children(self) -> list[RootChildStatistics]: ...
    @property
    def telemetry(self) -> SearchTelemetry: ...

def inverse_symmetry(symmetry: Symmetry) -> Symmetry: ...
def transform_action(action: int, board_size: int, symmetry: Symmetry) -> int: ...
def transform_coordinate(row: int, column: int, board_size: int, symmetry: Symmetry) -> Coordinate: ...
def transform_encoding(encoding: GoEncoding, symmetry: Symmetry) -> GoEncoding: ...
def search_go_fixed(
    state: GoState,
    evaluator: Callable[[GoInferenceRequest], InferenceResult],
    configuration: FixedPuctConfiguration,
) -> SearchResult: ...
