from enum import IntEnum

MAXIMUM_HISTORY_LENGTH: int

class Stone(IntEnum):
    EMPTY: Stone
    BLACK: Stone
    WHITE: Stone

class Player(IntEnum):
    BLACK: Player
    WHITE: Player

class TerminationReason(IntEnum):
    ONGOING: TerminationReason
    TWO_PASSES: TerminationReason
    SAFETY_PLY_CAP: TerminationReason

class Symmetry(IntEnum):
    IDENTITY: Symmetry
    ROTATE_90: Symmetry
    ROTATE_180: Symmetry
    ROTATE_270: Symmetry
    REFLECT: Symmetry
    REFLECT_ROTATE_90: Symmetry
    REFLECT_ROTATE_180: Symmetry
    REFLECT_ROTATE_270: Symmetry

class Coordinate:
    @property
    def row(self) -> int: ...
    @property
    def column(self) -> int: ...

class GoRules:
    def __init__(
        self,
        board_size: int,
        komi_half_points: int,
        safety_ply_cap: int,
        history_length: int,
    ) -> None: ...
    @property
    def board_size(self) -> int: ...
    @property
    def komi_half_points(self) -> int: ...
    @property
    def safety_ply_cap(self) -> int: ...
    @property
    def history_length(self) -> int: ...

class AreaScore:
    @property
    def black_twice(self) -> int: ...
    @property
    def white_twice(self) -> int: ...
    @property
    def winner(self) -> Player | None: ...

class TerminalResult:
    @property
    def reason(self) -> TerminationReason: ...
    @property
    def score(self) -> AreaScore | None: ...
    @property
    def winner(self) -> Player | None: ...

class GoEncoding:
    @property
    def planes(self) -> int: ...
    @property
    def board_size(self) -> int: ...
    @property
    def values(self) -> list[int]: ...
    def at(self, plane: int, row: int, column: int) -> int: ...

class GoState:
    def __init__(self, rules: GoRules) -> None: ...
    @classmethod
    def restore(
        cls,
        rules: GoRules,
        board: list[Stone],
        current_player: Player,
        ply: int,
        consecutive_passes: int,
        position_history: list[list[Stone]],
    ) -> GoState: ...
    @property
    def rules(self) -> GoRules: ...
    @property
    def board_size(self) -> int: ...
    @property
    def action_count(self) -> int: ...
    @property
    def pass_action(self) -> int: ...
    @property
    def current_player(self) -> Player: ...
    @property
    def ply(self) -> int: ...
    @property
    def consecutive_passes(self) -> int: ...
    @property
    def board(self) -> list[Stone]: ...
    def is_legal(self, action: int) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def apply(self, action: int) -> None: ...
    @property
    def termination_reason(self) -> TerminationReason: ...
    @property
    def is_terminal(self) -> bool: ...
    def terminal_result(self) -> TerminalResult: ...
    def area_score(self) -> AreaScore: ...
    def canonical_encoding(self) -> GoEncoding: ...
    def copy(self) -> GoState: ...
    def state_hash(self) -> int: ...

def inverse_symmetry(symmetry: Symmetry) -> Symmetry: ...
def transform_action(action: int, board_size: int, symmetry: Symmetry) -> int: ...
def transform_coordinate(row: int, column: int, board_size: int, symmetry: Symmetry) -> Coordinate: ...
def transform_encoding(encoding: GoEncoding, symmetry: Symmetry) -> GoEncoding: ...
