import time
from chess import Board, Move

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.eval.GUI import BaseGridGameGUI

move_list = [
    Move.from_uci('g2g3'),
    Move.from_uci('b7b6'),
    Move.from_uci('e2e4'),
    Move.from_uci('g8f6'),
    Move.from_uci('e4e5'),
    Move.from_uci('g7g6'),
    Move.from_uci('f1c4'),
    Move.from_uci('a7a5'),
    Move.from_uci('c4d5'),
    Move.from_uci('b8c6'),
    Move.from_uci('e5f6'),
    Move.from_uci('b6b5'),
    Move.from_uci('d5c6'),
    Move.from_uci('a8b8'),
    Move.from_uci('c6g2'),
    Move.from_uci('g6g5'),
    Move.from_uci('d1g4'),
    Move.from_uci('c8b7'),
    Move.from_uci('e1e2'),
    Move.from_uci('f8g7'),
    Move.from_uci('g4d7'),
    Move.from_uci('d8d7'),
    Move.from_uci('b2b4'),
    Move.from_uci('d7g4'),
    Move.from_uci('f2f3'),
    Move.from_uci('b7a6'),
    Move.from_uci('e2d1'),
    Move.from_uci('h7h5'),
    Move.from_uci('c1b2'),
    Move.from_uci('b8d8'),
    Move.from_uci('h2h3'),
    Move.from_uci('d8d4'),
    Move.from_uci('f3g4'),
    Move.from_uci('g7f6'),
    Move.from_uci('h1h2'),
    Move.from_uci('d4e4'),
    Move.from_uci('g2f1'),
    Move.from_uci('e4b4'),
    Move.from_uci('c2c4'),
    Move.from_uci('b4a4'),
    Move.from_uci('f1e2'),
    Move.from_uci('a6b7'),
    Move.from_uci('b2c3'),
    Move.from_uci('b7a6'),
    Move.from_uci('c3a5'),
    Move.from_uci('b5c4'),
    Move.from_uci('d1c2'),
    Move.from_uci('e8g8'),
    Move.from_uci('e2d3'),
    Move.from_uci('f6c3'),
    Move.from_uci('a2a3'),
    Move.from_uci('g8g7'),
    Move.from_uci('g1e2'),
    Move.from_uci('a6b5'),
    Move.from_uci('c2c3'),
    Move.from_uci('h5g4'),
    Move.from_uci('c3d4'),
    Move.from_uci('g7h6'),
    Move.from_uci('h3h4'),
    Move.from_uci('f8e8'),
    Move.from_uci('d4e5'),
    Move.from_uci('a4b4'),
    Move.from_uci('d3h7'),
    Move.from_uci('b5a6'),
    Move.from_uci('h7f5'),
    Move.from_uci('b4b1'),
    Move.from_uci('h4g5'),
    Move.from_uci('h6g7'),
    Move.from_uci('a5c3'),
    Move.from_uci('e7e6'),
    Move.from_uci('h2f2'),
    Move.from_uci('g7h8'),
    Move.from_uci('f2f1'),
    Move.from_uci('b1b7'),
    Move.from_uci('a1b1'),
    Move.from_uci('b7b4'),
    Move.from_uci('e5d4'),
    Move.from_uci('b4b1'),
    Move.from_uci('f5e6'),
    Move.from_uci('b1b5'),
    Move.from_uci('c3a5'),
    Move.from_uci('b5g5'),
    Move.from_uci('a5b4'),
    Move.from_uci('a6c8'),
    Move.from_uci('f1f5'),
    Move.from_uci('f7e6'),
    Move.from_uci('b4c5'),
    Move.from_uci('c7c6'),
    Move.from_uci('f5f4'),
    Move.from_uci('g5f5'),
    Move.from_uci('c5d6'),
    Move.from_uci('e8d8'),
    Move.from_uci('f4f2'),
    Move.from_uci('f5a5'),
    Move.from_uci('f2f6'),
    Move.from_uci('h8g8'),
    Move.from_uci('d4c4'),
    Move.from_uci('g8h7'),
    Move.from_uci('e2c3'),
    Move.from_uci('h7g7'),
    Move.from_uci('f6f7'),
    Move.from_uci('g7h6'),
    Move.from_uci('d6b4'),
    Move.from_uci('d8e8'),
    Move.from_uci('f7f6'),
    Move.from_uci('h6h7'),
    Move.from_uci('b4f8'),
    Move.from_uci('a5a6'),
    Move.from_uci('f8c5'),
    Move.from_uci('h7g8'),
    Move.from_uci('c5d6'),
    Move.from_uci('a6a8'),
    Move.from_uci('d6f4'),
    Move.from_uci('c8d7'),
    Move.from_uci('f4e5'),
    Move.from_uci('e8b8'),
    Move.from_uci('c4c5'),
    Move.from_uci('b8d8'),
    Move.from_uci('c5b6'),
    Move.from_uci('d8b8'),
    Move.from_uci('b6c5'),
    Move.from_uci('b8b7'),
    Move.from_uci('c3b5'),
    Move.from_uci('b7c7'),
    Move.from_uci('f6e6'),
    Move.from_uci('a8c8'),
    Move.from_uci('c5c4'),
    Move.from_uci('g8f7'),
    Move.from_uci('e6e7'),
    Move.from_uci('f7g6'),
    Move.from_uci('c4d4'),
    Move.from_uci('c6c5'),
    Move.from_uci('d4d5'),
    Move.from_uci('g6h5'),
    Move.from_uci('e7h7'),
    Move.from_uci('h5g6'),
    Move.from_uci('b5c3'),
    Move.from_uci('c8e8'),
    Move.from_uci('e5f6'),
    Move.from_uci('c7a7'),
    Move.from_uci('f6e7'),
    Move.from_uci('e8f8'),
    Move.from_uci('d5e5'),
    Move.from_uci('a7a4'),
    Move.from_uci('e7c5'),
    Move.from_uci('a4a8'),
    Move.from_uci('h7h4'),
    Move.from_uci('f8c8'),
    Move.from_uci('h4h6'),
    Move.from_uci('g6f7'),
    Move.from_uci('h6b6'),
    Move.from_uci('a8a5'),
    Move.from_uci('b6c6'),
    Move.from_uci('a5a6'),
    Move.from_uci('c6g6'),
    Move.from_uci('d7f5'),
    Move.from_uci('g6g4'),
    Move.from_uci('c8c5'),
    Move.from_uci('c3d5'),
    Move.from_uci('c5b5'),
    Move.from_uci('g4e4'),
    Move.from_uci('f5e4'),
    Move.from_uci('e5f4'),
    Move.from_uci('e4d3'),
    Move.from_uci('g3g4'),
    Move.from_uci('d3h7'),
    Move.from_uci('f4e5'),
    Move.from_uci('a6d6'),
    Move.from_uci('g4g5'),
    Move.from_uci('d6b6'),
    Move.from_uci('a3a4'),
    Move.from_uci('h7b1'),
    Move.from_uci('g5g6'),
    Move.from_uci('f7f8'),
    Move.from_uci('g6g7'),
    Move.from_uci('f8f7'),
    Move.from_uci('d2d3'),
    Move.from_uci('b5a5'),
    Move.from_uci('e5e4'),
    Move.from_uci('b6b7'),
    Move.from_uci('d5e3'),
    Move.from_uci('a5c5'),
    Move.from_uci('g7g8q'),
    Move.from_uci('f7e7'),
    Move.from_uci('e3c2'),
    Move.from_uci('c5a5'),
    Move.from_uci('g8b3'),
    Move.from_uci('a5g5'),
    Move.from_uci('c2e3'),
    Move.from_uci('b1d3'),
    Move.from_uci('e4d4'),
    Move.from_uci('d3c2'),
    Move.from_uci('b3a2'),
    Move.from_uci('b7b5'),
    Move.from_uci('a2b3'),
    Move.from_uci('c2b3'),
    Move.from_uci('e3g4'),
    Move.from_uci('b3a4'),
    Move.from_uci('g4f2'),
    Move.from_uci('e7f8'),
    Move.from_uci('f2d1'),
    Move.from_uci('b5f5'),
    Move.from_uci('d4e3'),
    Move.from_uci('f5d5'),
    Move.from_uci('d1b2'),
    Move.from_uci('g5g8'),
    Move.from_uci('b2d3'),
    Move.from_uci('a4d7'),
    Move.from_uci('e3f2'),
    Move.from_uci('f8e8'),
    Move.from_uci('d3f4'),
    Move.from_uci('d5d4'),
    Move.from_uci('f4g6'),
    Move.from_uci('d4d2'),
    Move.from_uci('f2f3'),
    Move.from_uci('g8g7'),
    Move.from_uci('f3g3'),
    Move.from_uci('d7f5'),
    Move.from_uci('g3f3'),
    Move.from_uci('d2d6'),
    Move.from_uci('f3g3'),
    Move.from_uci('e8d8'),
    Move.from_uci('g3h4'),
    Move.from_uci('f5d3'),
    Move.from_uci('h4g5'),
    Move.from_uci('g7g6'),
    Move.from_uci('g5h4'),
    Move.from_uci('d8d7'),
    Move.from_uci('h4h3'),
    Move.from_uci('g6g4'),
    Move.from_uci('h3h2'),
    Move.from_uci('g4h4'),
    Move.from_uci('h2g3'),
    Move.from_uci('d7c8'),
    Move.from_uci('g3g2'),
    Move.from_uci('h4h5'),
    Move.from_uci('g2g1'),
    Move.from_uci('h5f5'),
    Move.from_uci('g1h1'),
    Move.from_uci('f5f3'),
    Move.from_uci('h1g2'),
    Move.from_uci('c8b7'),
    Move.from_uci('g2g1'),
    Move.from_uci('d3a6'),
    Move.from_uci('g1g2'),
    Move.from_uci('f3f2'),
    Move.from_uci('g2h1'),
    Move.from_uci('d6g6'),
]

current_displayed_board = 0


def display_board(move_index: int, gui: BaseGridGameGUI):
    from src.settings import CurrentBoard, CurrentGameVisuals

    board = Board()
    for i in range(move_index):
        board.push(move_list[i])

    chess_board = CurrentBoard()
    chess_board.board = board

    gui.clear_highlights_and_redraw(lambda: CurrentGameVisuals.draw_pieces(chess_board, gui))
    gui.update_display()


def main():
    from src.eval.GUI import BaseGridGameGUI

    gui = BaseGridGameGUI(8, 8)

    current_displayed_board = 0

    display_board(current_displayed_board, gui)

    while True:
        events = gui.events_occurred()
        if events.quit:
            exit()

        if events.left:
            # Go back in history
            if current_displayed_board > 0:
                current_displayed_board -= 1
                display_board(current_displayed_board, gui)

        if events.right:
            # Go forward in history
            if current_displayed_board < len(move_list) - 1:
                current_displayed_board += 1
                display_board(current_displayed_board, gui)

        time.sleep(0.2)


if __name__ == '__main__':
    main()
