extends: vast-chess-8gpu-progressive-v43-katago-init-int8.yaml

run:
  run_name: vast-chess-8gpu-progressive-v43-katago-init-int8-r2
  tensorboard_run_directory: vast-chess-8gpu-progressive-v43-katago-init-int8-r2

training:
  save_path: py/training_data/production/vast-chess-8gpu-progressive-v43-katago-init-int8-r2
  limits:
    manual_stop_file: /workspace/run-control/stop/vast-chess-8gpu-progressive-v43-katago-init-int8-r2.stop

chess:
  self_play:
    inference:
      backend:
        kind: tensorrt
        bootstrap_with_torchscript: true
        templates:
        - kind: qat
          model_id: chess-cnn-scaled-post-12x128-fromto-int8
          phase: pre_fold
          engine_path: /workspace/tensorrt/v43-int8-12x128-prefold-production-template.engine
        - kind: qat
          model_id: chess-cnn-scaled-post-12x128-fromto-int8
          phase: deployment
          engine_path: /workspace/tensorrt/v36-int8-12x128-deployment-trained-template.engine
        - kind: qat
          model_id: chess-cnn-scaled-post-14x160-fromto-int8
          phase: pre_fold
          engine_path: /workspace/tensorrt/v36-int8-14x160-prefold-production-template.engine
        - kind: qat
          model_id: chess-cnn-scaled-post-14x160-fromto-int8
          phase: deployment
          engine_path: /workspace/tensorrt/v36-int8-14x160-deployment-trained-template.engine
