extends: vast-chess-8gpu-v83-v34-small-fp16-adamw008-reuse625-90m.yaml

run:
  run_name: vast-chess-8gpu-v84-v34-small-fp16-adamw008-reuse4-90m
  tensorboard_run_directory: vast-chess-8gpu-v84-v34-small-fp16-adamw008-reuse4-90m

training:
  save_path: py/training_data/production/vast-chess-8gpu-v84-v34-small-fp16-adamw008-reuse4-90m
  lifecycle:
    credit:
      replay_ratio: 4
  limits:
    manual_stop_file: /workspace/run-control/stop/vast-chess-8gpu-v84-v34-small-fp16-adamw008-reuse4-90m.stop
