from __future__ import annotations

from typing import Protocol


class StopSignal(Protocol):
    def is_set(self) -> bool: ...

    def set(self) -> None: ...


class RuntimeControlSignal(StopSignal, Protocol):
    def wait_for_experiment_start(self) -> int: ...


class ByteQueue(Protocol):
    def put(self, value: bytes) -> None: ...

    def get(self, block: bool = True, timeout: float | None = None) -> bytes: ...

    def close(self) -> None: ...

    def join_thread(self) -> None: ...
