extends: 00-baseline.yaml
run:
  run_name: go7-overnight-04-mixed-search-25-full
  tensorboard_run_directory: go7-overnight-04-mixed-search-25-full
training:
  save_path: py/training_data/screening/go7-overnight/04-mixed-search-25-full
go:
  self_play:
    full_search_probability: {kind: constant, value: 0.25}
