extends: 00-baseline.yaml
run:
  run_name: go7-overnight-06-progressive-search-64-512
  tensorboard_run_directory: go7-overnight-06-progressive-search-64-512
training:
  save_path: py/training_data/screening/go7-overnight/06-progressive-search-64-512
go:
  self_play:
    search:
      full_searches: {kind: linear, start_generation: 0, end_generation: 60, start_value: 64, end_value: 512, rounding: nearest}
