extends: 00-baseline.yaml
run:
  run_name: go7-overnight-10-random-opening-12
  tensorboard_run_directory: go7-overnight-10-random-opening-12
training:
  save_path: py/training_data/screening/go7-overnight/10-random-opening-12
go:
  self_play:
    maximum_random_opening_plies: {kind: constant, value: 12}
