extends: 00-baseline.yaml
run:
  run_name: go7-overnight-12-fpu-reduction-02
  tensorboard_run_directory: go7-overnight-12-fpu-reduction-02
training:
  save_path: py/training_data/screening/go7-overnight/12-fpu-reduction-02
go:
  self_play:
    search:
      first_play_urgency:
        kind: reduced_parent_value
        reduction: 0.2
