extends: 00-medium-8x96.yaml
run:
  run_name: go9-model-size-02-large-10x128
  tensorboard_run_directory: go9-model-size-02-large-10x128
training:
  save_path: py/training_data/screening/go9-model-size/02-large-10x128
  network:
    num_layers: 10
    hidden_size: 128
