extends: ../../baselines/vast-go-9x9-2gpu-4h.yaml
run:
  run_name: go9-strong-00-baseline
  tensorboard_run_directory: go9-strong-00-baseline
training:
  save_path: py/training_data/screening/go9-strong/00-baseline
