extends: 00-baseline.yaml
run:
  run_name: go9-strong-01-zero-fpu
  tensorboard_run_directory: go9-strong-01-zero-fpu
training:
  save_path: py/training_data/screening/go9-strong/01-zero-fpu
go:
  self_play:
    search:
      first_play_urgency: {kind: zero}
