extends: 00-baseline.yaml
run:
  run_name: go9-strong-03-squeeze-excitation
  tensorboard_run_directory: go9-strong-03-squeeze-excitation
training:
  save_path: py/training_data/screening/go9-strong/03-squeeze-excitation
  network:
    residual_context:
      kind: squeeze_excitation
      placement: every_second_block
